wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1649912194
    t:
      1:
      - 5
      - 6
      - 8
      - 53
      - 55
      4: 3.8.13
      5: 0.12.14
      8:
      - 1
      - 4
      - 5
